/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":lib"))
    implementation("org.apache.commons:commons-text")

}

application {
    // Define the main class for the application.
    mainClass = "za.jvexpress.app.Main"
}
