/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}



application {
    // Define the main class for the application.
    mainClass = "za.jvexpress.Server"
}
